# Generated by Django 2.0.1 on 2018-01-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PH')),
                ('DO', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='溶解氧')),
                ('NH3N', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='氨氮')),
                ('CODMn', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='高锰酸盐')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
    ]
