# Generated by Django 2.0.1 on 2018-01-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WQPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualityrecord',
            name='CODMn',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='高锰酸盐'),
        ),
        migrations.AlterField(
            model_name='waterqualityrecord',
            name='DO',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='溶解氧'),
        ),
        migrations.AlterField(
            model_name='waterqualityrecord',
            name='NH3N',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='氨氮'),
        ),
        migrations.AlterField(
            model_name='waterqualityrecord',
            name='PH',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='PH'),
        ),
    ]
